version: '3.7'
services:
  php:
    image: yiisoftware/yii-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paradam
      MYSQL_USER: splaa
      MYSQL_PASSWORD: splaa1977
    volumes:
      - "./database:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080